Repository MarkusAmshove/Kluent, pull requests merged in 2022-10, with the labels that each got.

#209 Update junit dependency to non-vulnerable version
  build.gradle
Labels: dependencies

#210 Add shouldContainNone and shouldNotContainAny with check lambda
  AUTHORS.md
  common/src/main/kotlin/org/amshove/kluent/Collections.kt
  common/src/test/kotlin/org/amshove/kluent/tests/collections/ShouldContainNoneWithCheckShould.kt
  common/src/test/kotlin/org/amshove/kluent/tests/collections/ShouldNotContainAnyWithCheckShould.kt
Labels: enhancement

#211 Fix order of ByteArray assertion params
  AUTHORS.md
  common/src/main/kotlin/org/amshove/kluent/Collections.kt
Labels: bug

#219 Fix target Java version
  build.gradle
  common/build.gradle
Labels: bug

#221 Target Java 8
  build.gradle
  common/build.gradle
  jvm/build.gradle
Labels: bug

#224 Enforce Java version during publish
  build.gradle
  publishAll.sh
Labels: chore

#222 feat(build): Use java matrix in github action
  .github/workflows/main.yml
  AUTHORS.md
Labels: maintenance
